# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tally < Formula
  desc "CLI time tracking utility"
  homepage "https://github.com/thinktide/tally"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/thinktide/tally/releases/download/v0.1.0/tally_0.1.0_darwin_amd64.tar.gz"
    sha256 "4502f4a018c35de13b1771c42b1b43bd3aef66c8bc406fc5d124d12b5cc1d836"

    def install
      bin.install "tally"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/thinktide/tally/releases/download/v0.1.0/tally_0.1.0_darwin_arm64.tar.gz"
    sha256 "d576602dcf5d5af093b2554aacf5d953065a8e3b5d87d8a6825f8c0dda39b2a4"

    def install
      bin.install "tally"
    end
  end

  test do
    system "#{bin}/tally", "version"
  end
end
