# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tally < Formula
  desc "CLI time tracking utility"
  homepage "https://github.com/thinktide/tally"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thinktide/tally/releases/download/v0.4.0/tally_0.4.0_darwin_amd64.tar.gz"
      sha256 "3ab667deb36c9bd5603a1dda4d78f69585d6474062046729792c66e7b036eae9"

      def install
        bin.install "tally"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thinktide/tally/releases/download/v0.4.0/tally_0.4.0_darwin_arm64.tar.gz"
      sha256 "2ed6e0d3495b91337ba92c0617f1bfc97540d52736b634b6a0f6f11d148a3eb7"

      def install
        bin.install "tally"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thinktide/tally/releases/download/v0.4.0/tally_0.4.0_linux_amd64.tar.gz"
      sha256 "c1493487121b2ccc0eab96ca10f9c1e8442c7f4412ea306153238b80848c4338"
      def install
        bin.install "tally"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thinktide/tally/releases/download/v0.4.0/tally_0.4.0_linux_arm64.tar.gz"
      sha256 "477409e6a954adf03d764e36d4f3d655bf89daf4ff82f0981828e1cafadb7a67"
      def install
        bin.install "tally"
      end
    end
  end

  test do
    system "#{bin}/tally", "version"
  end
end
